"""Seed company data for initial crawling."""

# Initial seed of tech companies with known ATS
# Priority: 100 = highest (crawl first), 0 = lowest
SEED_COMPANIES = [
    # ============================================
    # TIER 1: Top Tech Companies (Priority 90-100)
    # ============================================
    # Greenhouse companies
    {
        "name": "Stripe",
        "domain": "stripe.com",
        "careers_url": "https://stripe.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "stripe",
        "crawl_priority": 100,
    },
    {
        "name": "Airbnb",
        "domain": "airbnb.com",
        "careers_url": "https://careers.airbnb.com",
        "ats_type": "greenhouse",
        "ats_identifier": "airbnb",
        "crawl_priority": 100,
    },
    {
        "name": "Coinbase",
        "domain": "coinbase.com",
        "careers_url": "https://www.coinbase.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "coinbase",
        "crawl_priority": 95,
    },
    {
        "name": "Notion",
        "domain": "notion.so",
        "careers_url": "https://www.notion.so/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "notion",
        "crawl_priority": 95,
    },
    {
        "name": "Figma",
        "domain": "figma.com",
        "careers_url": "https://www.figma.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "figma",
        "crawl_priority": 95,
    },
    {
        "name": "Plaid",
        "domain": "plaid.com",
        "careers_url": "https://plaid.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "plaid",
        "crawl_priority": 90,
    },
    {
        "name": "Discord",
        "domain": "discord.com",
        "careers_url": "https://discord.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "discord",
        "crawl_priority": 95,
    },
    {
        "name": "Databricks",
        "domain": "databricks.com",
        "careers_url": "https://www.databricks.com/company/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "databricks",
        "crawl_priority": 95,
    },
    {
        "name": "Datadog",
        "domain": "datadoghq.com",
        "careers_url": "https://careers.datadoghq.com",
        "ats_type": "greenhouse",
        "ats_identifier": "datadog",
        "crawl_priority": 90,
    },
    {
        "name": "GitLab",
        "domain": "gitlab.com",
        "careers_url": "https://about.gitlab.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "gitlab",
        "crawl_priority": 90,
    },
    # Lever companies
    {
        "name": "Netflix",
        "domain": "netflix.com",
        "careers_url": "https://jobs.netflix.com",
        "ats_type": "lever",
        "ats_identifier": "netflix",
        "crawl_priority": 100,
    },
    {
        "name": "Cloudflare",
        "domain": "cloudflare.com",
        "careers_url": "https://www.cloudflare.com/careers",
        "ats_type": "lever",
        "ats_identifier": "cloudflare",
        "crawl_priority": 95,
    },
    {
        "name": "Ramp",
        "domain": "ramp.com",
        "careers_url": "https://ramp.com/careers",
        "ats_type": "lever",
        "ats_identifier": "ramp",
        "crawl_priority": 90,
    },
    {
        "name": "Retool",
        "domain": "retool.com",
        "careers_url": "https://retool.com/careers",
        "ats_type": "lever",
        "ats_identifier": "retool",
        "crawl_priority": 85,
    },
    {
        "name": "Vercel",
        "domain": "vercel.com",
        "careers_url": "https://vercel.com/careers",
        "ats_type": "lever",
        "ats_identifier": "vercel",
        "crawl_priority": 90,
    },
    # Ashby companies
    {
        "name": "Anthropic",
        "domain": "anthropic.com",
        "careers_url": "https://www.anthropic.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "anthropic",
        "crawl_priority": 100,
    },
    {
        "name": "OpenAI",
        "domain": "openai.com",
        "careers_url": "https://openai.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "openai",
        "crawl_priority": 100,
    },
    {
        "name": "Supabase",
        "domain": "supabase.com",
        "careers_url": "https://supabase.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "supabase",
        "crawl_priority": 90,
    },
    {
        "name": "Linear",
        "domain": "linear.app",
        "careers_url": "https://linear.app/careers",
        "ats_type": "ashby",
        "ats_identifier": "linear",
        "crawl_priority": 90,
    },
    {
        "name": "Resend",
        "domain": "resend.com",
        "careers_url": "https://resend.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "resend",
        "crawl_priority": 80,
    },
    # ============================================
    # TIER 2: High-Growth Startups (Priority 70-85)
    # ============================================
    {
        "name": "Deel",
        "domain": "deel.com",
        "careers_url": "https://www.deel.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "deel",
        "crawl_priority": 85,
    },
    {
        "name": "Rippling",
        "domain": "rippling.com",
        "careers_url": "https://www.rippling.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "rippling",
        "crawl_priority": 85,
    },
    {
        "name": "Brex",
        "domain": "brex.com",
        "careers_url": "https://www.brex.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "brex",
        "crawl_priority": 85,
    },
    {
        "name": "Scale AI",
        "domain": "scale.com",
        "careers_url": "https://scale.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "scaleai",
        "crawl_priority": 90,
    },
    {
        "name": "Airtable",
        "domain": "airtable.com",
        "careers_url": "https://airtable.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "airtable",
        "crawl_priority": 85,
    },
    {
        "name": "Webflow",
        "domain": "webflow.com",
        "careers_url": "https://webflow.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "webflow",
        "crawl_priority": 85,
    },
    {
        "name": "Canva",
        "domain": "canva.com",
        "careers_url": "https://www.canva.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "canva",
        "crawl_priority": 85,
    },
    {
        "name": "Mercury",
        "domain": "mercury.com",
        "careers_url": "https://mercury.com/jobs",
        "ats_type": "lever",
        "ats_identifier": "mercury",
        "crawl_priority": 85,
    },
    {
        "name": "Miro",
        "domain": "miro.com",
        "careers_url": "https://miro.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "miro",
        "crawl_priority": 80,
    },
    {
        "name": "Loom",
        "domain": "loom.com",
        "careers_url": "https://www.loom.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "loom",
        "crawl_priority": 80,
    },
    {
        "name": "Amplitude",
        "domain": "amplitude.com",
        "careers_url": "https://amplitude.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "amplitude",
        "crawl_priority": 80,
    },
    {
        "name": "PostHog",
        "domain": "posthog.com",
        "careers_url": "https://posthog.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "posthog",
        "crawl_priority": 80,
    },
    {
        "name": "Railway",
        "domain": "railway.app",
        "careers_url": "https://railway.app/careers",
        "ats_type": "ashby",
        "ats_identifier": "railway",
        "crawl_priority": 75,
    },
    {
        "name": "Render",
        "domain": "render.com",
        "careers_url": "https://render.com/careers",
        "ats_type": "lever",
        "ats_identifier": "render",
        "crawl_priority": 75,
    },
    {
        "name": "PlanetScale",
        "domain": "planetscale.com",
        "careers_url": "https://planetscale.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "planetscale",
        "crawl_priority": 80,
    },
    {
        "name": "Neon",
        "domain": "neon.tech",
        "careers_url": "https://neon.tech/careers",
        "ats_type": "ashby",
        "ats_identifier": "neon",
        "crawl_priority": 80,
    },
    # ============================================
    # TIER 3: YC Companies & Emerging (Priority 50-70)
    # ============================================
    {
        "name": "Cal.com",
        "domain": "cal.com",
        "careers_url": "https://cal.com/jobs",
        "ats_type": "ashby",
        "ats_identifier": "cal",
        "crawl_priority": 70,
    },
    {
        "name": "Dub",
        "domain": "dub.co",
        "careers_url": "https://dub.co/careers",
        "ats_type": "ashby",
        "ats_identifier": "dub",
        "crawl_priority": 65,
    },
    {
        "name": "Clerk",
        "domain": "clerk.com",
        "careers_url": "https://clerk.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "clerk",
        "crawl_priority": 75,
    },
    {
        "name": "Inngest",
        "domain": "inngest.com",
        "careers_url": "https://www.inngest.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "inngest",
        "crawl_priority": 65,
    },
    {
        "name": "Trigger.dev",
        "domain": "trigger.dev",
        "careers_url": "https://trigger.dev/careers",
        "ats_type": "ashby",
        "ats_identifier": "trigger",
        "crawl_priority": 65,
    },
    {
        "name": "Tinybird",
        "domain": "tinybird.co",
        "careers_url": "https://www.tinybird.co/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "tinybird",
        "crawl_priority": 70,
    },
    {
        "name": "Prisma",
        "domain": "prisma.io",
        "careers_url": "https://www.prisma.io/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "prisma",
        "crawl_priority": 75,
    },
    {
        "name": "Turso",
        "domain": "turso.tech",
        "careers_url": "https://turso.tech/careers",
        "ats_type": "ashby",
        "ats_identifier": "turso",
        "crawl_priority": 65,
    },
    {
        "name": "Upstash",
        "domain": "upstash.com",
        "careers_url": "https://upstash.com/careers",
        "ats_type": "ashby",
        "ats_identifier": "upstash",
        "crawl_priority": 70,
    },
    {
        "name": "Fly.io",
        "domain": "fly.io",
        "careers_url": "https://fly.io/jobs",
        "ats_type": "lever",
        "ats_identifier": "fly",
        "crawl_priority": 75,
    },
    {
        "name": "Sentry",
        "domain": "sentry.io",
        "careers_url": "https://sentry.io/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "sentry",
        "crawl_priority": 80,
    },
    {
        "name": "LaunchDarkly",
        "domain": "launchdarkly.com",
        "careers_url": "https://launchdarkly.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "launchdarkly",
        "crawl_priority": 75,
    },
    {
        "name": "Auth0",
        "domain": "auth0.com",
        "careers_url": "https://auth0.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "auth0",
        "crawl_priority": 80,
    },
    {
        "name": "HashiCorp",
        "domain": "hashicorp.com",
        "careers_url": "https://www.hashicorp.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "hashicorp",
        "crawl_priority": 85,
    },
    {
        "name": "Temporal",
        "domain": "temporal.io",
        "careers_url": "https://temporal.io/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "temporal",
        "crawl_priority": 75,
    },
    {
        "name": "Grafana Labs",
        "domain": "grafana.com",
        "careers_url": "https://grafana.com/about/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "grafanalabs",
        "crawl_priority": 80,
    },
    {
        "name": "Pulumi",
        "domain": "pulumi.com",
        "careers_url": "https://www.pulumi.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "pulumi",
        "crawl_priority": 70,
    },
    {
        "name": "Snyk",
        "domain": "snyk.io",
        "careers_url": "https://snyk.io/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "snyk",
        "crawl_priority": 80,
    },
    {
        "name": "Kong",
        "domain": "konghq.com",
        "careers_url": "https://konghq.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "kong",
        "crawl_priority": 75,
    },
    {
        "name": "CircleCI",
        "domain": "circleci.com",
        "careers_url": "https://circleci.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "circleci",
        "crawl_priority": 75,
    },
    # ============================================
    # TIER 4: More Companies (Priority 40-60)
    # ============================================
    {
        "name": "Twilio",
        "domain": "twilio.com",
        "careers_url": "https://www.twilio.com/company/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "twilio",
        "crawl_priority": 80,
    },
    {
        "name": "Segment",
        "domain": "segment.com",
        "careers_url": "https://segment.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "segment",
        "crawl_priority": 75,
    },
    {
        "name": "Mixpanel",
        "domain": "mixpanel.com",
        "careers_url": "https://mixpanel.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "mixpanel",
        "crawl_priority": 70,
    },
    {
        "name": "Intercom",
        "domain": "intercom.com",
        "careers_url": "https://www.intercom.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "intercom",
        "crawl_priority": 80,
    },
    {
        "name": "Asana",
        "domain": "asana.com",
        "careers_url": "https://asana.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "asana",
        "crawl_priority": 80,
    },
    {
        "name": "Atlassian",
        "domain": "atlassian.com",
        "careers_url": "https://www.atlassian.com/company/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "atlassian",
        "crawl_priority": 85,
    },
    {
        "name": "HubSpot",
        "domain": "hubspot.com",
        "careers_url": "https://www.hubspot.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "hubspot",
        "crawl_priority": 85,
    },
    {
        "name": "Zapier",
        "domain": "zapier.com",
        "careers_url": "https://zapier.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "zapier",
        "crawl_priority": 80,
    },
    {
        "name": "Monday.com",
        "domain": "monday.com",
        "careers_url": "https://monday.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "mondaycom",
        "crawl_priority": 80,
    },
    {
        "name": "Gusto",
        "domain": "gusto.com",
        "careers_url": "https://gusto.com/about/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "gusto",
        "crawl_priority": 80,
    },
    {
        "name": "Square",
        "domain": "squareup.com",
        "careers_url": "https://careers.squareup.com",
        "ats_type": "greenhouse",
        "ats_identifier": "squareup",
        "crawl_priority": 85,
    },
    {
        "name": "Robinhood",
        "domain": "robinhood.com",
        "careers_url": "https://robinhood.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "robinhood",
        "crawl_priority": 85,
    },
    {
        "name": "Chime",
        "domain": "chime.com",
        "careers_url": "https://www.chime.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "chime",
        "crawl_priority": 80,
    },
    {
        "name": "Instacart",
        "domain": "instacart.com",
        "careers_url": "https://instacart.careers",
        "ats_type": "greenhouse",
        "ats_identifier": "instacart",
        "crawl_priority": 85,
    },
    {
        "name": "DoorDash",
        "domain": "doordash.com",
        "careers_url": "https://careers.doordash.com",
        "ats_type": "greenhouse",
        "ats_identifier": "doordash",
        "crawl_priority": 85,
    },
    {
        "name": "Lyft",
        "domain": "lyft.com",
        "careers_url": "https://www.lyft.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "lyft",
        "crawl_priority": 85,
    },
    {
        "name": "Spotify",
        "domain": "spotify.com",
        "careers_url": "https://www.lifeatspotify.com",
        "ats_type": "greenhouse",
        "ats_identifier": "spotify",
        "crawl_priority": 90,
    },
    {
        "name": "Shopify",
        "domain": "shopify.com",
        "careers_url": "https://www.shopify.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "shopify",
        "crawl_priority": 90,
    },
    {
        "name": "Slack",
        "domain": "slack.com",
        "careers_url": "https://slack.com/careers",
        "ats_type": "greenhouse",
        "ats_identifier": "slack",
        "crawl_priority": 85,
    },
    {
        "name": "Dropbox",
        "domain": "dropbox.com",
        "careers_url": "https://www.dropbox.com/jobs",
        "ats_type": "greenhouse",
        "ats_identifier": "dropbox",
        "crawl_priority": 85,
    },
]

# Count by ATS type
def get_seed_stats() -> dict:
    """Get statistics about seed companies."""
    stats = {"total": len(SEED_COMPANIES), "by_ats": {}}
    for company in SEED_COMPANIES:
        ats = company.get("ats_type", "unknown")
        stats["by_ats"][ats] = stats["by_ats"].get(ats, 0) + 1
    return stats
