export const TECH_FIELDS = [
  'Software Engineering',
  'Frontend Development',
  'Backend Development',
  'Full Stack Development',
  'Mobile Development (iOS)',
  'Mobile Development (Android)',
  'DevOps / SRE',
  'Cloud / Infrastructure',
  'Data Engineering',
  'Data Science',
  'Machine Learning / AI',
  'Security Engineering',
  'QA / Testing',
  'Product Management',
  'Product Design',
  'UX Research',
  'UI/UX Design',
  'Technical Program Management',
  'Engineering Management',
  'Solutions Architecture',
  'Technical Writing',
  'Developer Relations',
  'Sales Engineering',
  'Sales / Account Executive',
  'Business Development',
  'Customer Success',
  'Marketing',
  'Growth Marketing',
  'Content Marketing',
  'Product Marketing',
  'Operations',
  'People / HR',
  'Finance',
  'Legal',
  'Other',
] as const

export const SENIORITY_LEVELS = [
  'Intern',
  'Junior / Entry Level',
  'Mid-Level',
  'Senior',
  'Staff / Principal',
  'Director',
  'VP',
  'C-Level / Executive',
] as const

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Germany',
  'France',
  'Netherlands',
  'Ireland',
  'Australia',
  'New Zealand',
  'Singapore',
  'India',
  'Japan',
  'South Korea',
  'Israel',
  'United Arab Emirates',
  'Brazil',
  'Mexico',
  'Argentina',
  'Spain',
  'Italy',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Switzerland',
  'Austria',
  'Belgium',
  'Poland',
  'Portugal',
  'Czech Republic',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Egypt',
  'Philippines',
  'Vietnam',
  'Thailand',
  'Indonesia',
  'Malaysia',
  'China',
  'Taiwan',
  'Hong Kong',
  'Other',
] as const

export const WORK_TYPES = [
  { id: 'remote', label: 'Remote' },
  { id: 'hybrid', label: 'Hybrid' },
  { id: 'onsite', label: 'On-site' },
] as const

export const ROLE_TYPES = [
  { id: 'permanent', label: 'Permanent / Full-time' },
  { id: 'contract', label: 'Contract' },
  { id: 'freelance', label: 'Freelance' },
] as const
